### ISSUE TITLE
Custom Material Style

### ISSUE THREAD

**Issue by andersonkxiass** [Kairos-Project/kairos-framework#2]
Hi,

It is a  great idea, I'm excited to use it! could you provide some help about how to make custom material style? I would like to change some behaviors.

thanks!

**Comment by marconi1992** [comment]
the default theme is based in the color palette from material design, https://www.google.com/design/spec/style/color.html#color-color-schemes, you can override the palette in a custom stylesheet

``` css
*{
    -color-primary:#009688;
    -color-dark-primary:#00796B;
    -color-accent:#E91E63;

}
```

Actually i'm working in a more flexible theming.
